### ISSUE TITLE
(bug) notification controller "create" not working

### ISSUE THREAD

**Issue by uap-dev** [logicalGoldfish/LenderBee#230]
[Error: ER_BAD_FIELD_ERROR: Unknown column 'Users.Notification.userreq_id' in 'field list']
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     index: 0,

**Comment by TroutZen** [comment]
Removed the classMethods on the Items Model b/c the association was breaking:

// {
//     classMethods: {
//       associate: function(models) {
//         models.Item.belongsToMany(models.User, {
//           through: models.Notification,
//           foreignKey: 'itemreq_id'
//         });
//       }
//     }
//   }
